### PR TITLE
[WIP] Allow for seekable encryption of attachments

### PR DESCRIPTION
**Pull request by elevine**
See: https://github.com/couchbase/couchbase-lite-net/issues/621

### CODE REVIEW

**Comment by Ariemeth** [comment]
looks good so far

**Comment by elevine** [comment]
We're struggling to get the Android unit tests running.  As a result, I'm planning to add a new sample Android app to test and demo the seekable encryption.

**Comment by orenfromberg** [comment]
so far so good :+1:

**Comment by elevine** [comment]
I broke out the change that allows different symmetric key implementation to be used into PR #3.  Won't proceed with building a demo app at this time.

**Pull request closed without merging**
